-- Crypto donations: one deterministic BIP32 deposit address per user, the
-- same address on every EVM-compatible chain (same secp256k1 curve, same
-- derivation, only the RPC endpoint and token contracts differ). Deposits
-- are watched on-chain and credited to the user's Stars balance once they
-- reach the chain's configured confirmation depth.
--
-- The master seed is stored encrypted (AES-256-GCM, key from
-- TELESRV_DONATION_WALLET_KEY, never in this database) and is only ever
-- decrypted to derive a watch address or -- operator-triggered only, never
-- automatic -- to sign a sweep transaction. Normal deposit detection and
-- crediting never touches the private key at all.

CREATE TABLE public.donation_wallet (
    id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    encrypted_seed bytea NOT NULL,
    nonce bytea NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE public.donation_address_index_seq START WITH 1;

CREATE TABLE public.donation_addresses (
    user_id bigint PRIMARY KEY,
    derivation_index bigint DEFAULT nextval('public.donation_address_index_seq') NOT NULL,
    address text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT donation_addresses_address_uniq UNIQUE (address),
    CONSTRAINT donation_addresses_index_uniq UNIQUE (derivation_index),
    CONSTRAINT donation_addresses_address_check CHECK (address ~ '^0x[0-9a-f]{40}$')
);

CREATE TABLE public.donation_chains (
    chain_key text PRIMARY KEY,
    name text NOT NULL,
    chain_id bigint NOT NULL,
    rpc_url text DEFAULT '' NOT NULL,
    ws_url text DEFAULT '' NOT NULL,
    native_symbol text NOT NULL,
    native_decimals integer NOT NULL,
    confirmations_required integer DEFAULT 10 NOT NULL,
    price_feed_address text DEFAULT '' NOT NULL,
    -- Manual USD-per-native-unit fallback (scaled by 1e6) for chains with no
    -- Chainlink feed configured (local Ganache, or before one is set).
    manual_usd_rate_micros bigint DEFAULT 0 NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT donation_chains_decimals_check CHECK (native_decimals > 0 AND native_decimals <= 30),
    CONSTRAINT donation_chains_confirmations_check CHECK (confirmations_required > 0)
);

CREATE TABLE public.donation_tokens (
    chain_key text NOT NULL REFERENCES public.donation_chains(chain_key) ON DELETE CASCADE,
    symbol text NOT NULL,
    contract_address text DEFAULT '' NOT NULL,
    decimals integer NOT NULL,
    PRIMARY KEY (chain_key, symbol),
    CONSTRAINT donation_tokens_decimals_check CHECK (decimals > 0 AND decimals <= 30)
);

CREATE TABLE public.donation_chain_cursors (
    chain_key text PRIMARY KEY REFERENCES public.donation_chains(chain_key) ON DELETE CASCADE,
    last_scanned_block bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.donation_deposits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    chain_key text NOT NULL REFERENCES public.donation_chains(chain_key),
    -- '' = the chain's native currency; otherwise a symbol in donation_tokens.
    token_symbol text DEFAULT '' NOT NULL,
    tx_hash text NOT NULL,
    -- -1 for a native transfer (no log index); the ERC-20 Transfer log index
    -- otherwise, so two token transfers in one tx are distinct deposits.
    log_index integer DEFAULT '-1' NOT NULL,
    block_number bigint NOT NULL,
    amount_raw numeric(78,0) NOT NULL,
    usd_value_micros bigint DEFAULT 0 NOT NULL,
    stars_credited bigint DEFAULT 0 NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    confirmations integer DEFAULT 0 NOT NULL,
    detected_at timestamp with time zone DEFAULT now() NOT NULL,
    credited_at timestamp with time zone,
    CONSTRAINT donation_deposits_tx_uniq UNIQUE (chain_key, tx_hash, log_index),
    CONSTRAINT donation_deposits_amount_check CHECK (amount_raw > 0),
    CONSTRAINT donation_deposits_status_check CHECK (status IN ('pending','confirmed','credited','orphaned')),
    CONSTRAINT donation_deposits_credited_check CHECK (
        (status = 'credited') = (credited_at IS NOT NULL AND stars_credited > 0)
    )
);
CREATE INDEX donation_deposits_user_idx ON public.donation_deposits(user_id, detected_at DESC);
CREATE INDEX donation_deposits_pending_idx ON public.donation_deposits(chain_key, status) WHERE status IN ('pending','confirmed');

-- Seed the chain registry. Only Sepolia and local Ganache are enabled --
-- everything else ships as a disabled row (empty rpc_url) the operator
-- fills in and flips on later without a migration.
-- manual_usd_rate_micros is a placeholder testing rate (USD per 1 whole
-- native unit, *1e6) until a Chainlink feed is wired in per
-- domain.DonationChain.PriceFeedAddress -- an operator should update it to
-- track the real market rate, especially before enabling mainnet/L2 rows.
INSERT INTO public.donation_chains (chain_key, name, chain_id, rpc_url, ws_url, native_symbol, native_decimals, confirmations_required, manual_usd_rate_micros, enabled) VALUES
    ('ganache', 'Ganache (local)', 1337, 'http://127.0.0.1:7545', '', 'ETH', 18, 1, 2000000000, true),
    ('sepolia', 'Sepolia (testnet)', 11155111, '', '', 'ETH', 18, 10, 2000000000, true),
    ('ethereum', 'Ethereum', 1, '', '', 'ETH', 18, 12, 2000000000, false),
    ('base', 'Base', 8453, '', '', 'ETH', 18, 12, 2000000000, false),
    ('polygon', 'Polygon', 137, '', '', 'MATIC', 18, 20, 500000, false),
    ('bsc', 'BNB Smart Chain', 56, '', '', 'BNB', 18, 12, 600000000, false);

-- Sepolia USDC is Circle's own canonical testnet deployment, verified
-- against Circle's published faucet/contract docs. There is no equivalent
-- official Tether USDT deployment on Sepolia to cite with confidence, so
-- that row (and every Ganache/mainnet/L2 token row) ships with an empty
-- contract_address for the operator to fill in -- Ganache needs a locally
-- deployed mock ERC-20 stand-in regardless, since it has no real
-- stablecoins at all.
INSERT INTO public.donation_tokens (chain_key, symbol, contract_address, decimals) VALUES
    ('sepolia', 'USDC', '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238', 6),
    ('sepolia', 'USDT', '', 6);
