name: Build OwpenGram Admin Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true

      - name: Build Admin Panel for Android ARM64
        env:
          CGO_ENABLED: '0'
          GOOS: android
          GOARCH: arm64
        run: |
          go build -p 4 -o admin-panel ./cmd/telesrv-admin
          file admin-panel

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: OwpenGram-Admin-Android-ARM64
          path: admin-panel
          retention-days: 30
