name: Build OwpenGram Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
          cache: true

      - name: Build Android ARM64
        run: |
          CGO_ENABLED=0 GOOS=android GOARCH=arm64 \
          go build -p 4 -o gramsrv ./cmd/telesrv

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: OwpenGram-Android-ARM64
          path: gramsrv
